// Week-by-week pregnancy development data (weeks 4-40).

export interface WeekInfo {
  size: string;
  sizeCompare: string;
  length: string;
  weight: string;
  development: string;
  milestone: string;
  trimester: 1 | 2 | 3;
  maternalChanges: string;
  weeklyTip: string;
}

export const WEEK_DATA: Record<number, WeekInfo> = {
  4: { size: 'Poppy seed', sizeCompare: 'a poppy seed', length: '0.4 mm', weight: '< 1 g', development: 'The embryo implants in the uterine lining and begins to grow.', milestone: 'Implantation occurs', trimester: 1, maternalChanges: 'You may notice light spotting as the embryo implants.', weeklyTip: 'Start taking a prenatal vitamin with folic acid if you haven\'t already.' },
  5: { size: 'Sesame seed', sizeCompare: 'a sesame seed', length: '1.5 mm', weight: '< 1 g', development: 'The neural tube — future brain and spinal cord — begins to form.', milestone: 'Neural tube forming', trimester: 1, maternalChanges: 'Fatigue and breast tenderness are common. Morning sickness may begin.', weeklyTip: 'Schedule your first prenatal appointment to confirm the pregnancy.' },
  6: { size: 'Lentil', sizeCompare: 'a lentil', length: '6 mm', weight: '< 1 g', development: 'The heart begins to beat and facial features start to take shape.', milestone: 'Heart starts beating', trimester: 1, maternalChanges: 'Nausea, food aversions, and frequent urination may intensify.', weeklyTip: 'Eat small, frequent meals to help manage nausea.' },
  7: { size: 'Blueberry', sizeCompare: 'a blueberry', length: '1.3 cm', weight: '< 1 g', development: 'Arms and legs emerge as small buds; the brain grows rapidly.', milestone: 'Limb buds appear', trimester: 1, maternalChanges: 'Your clothes may feel tighter even though you\'re not showing yet.', weeklyTip: 'Stay hydrated — aim for 8–10 glasses of water daily.' },
  8: { size: 'Raspberry', sizeCompare: 'a raspberry', length: '1.6 cm', weight: '1 g', development: 'Fingers and toes begin to form; all major organs are developing.', milestone: 'Fingers forming', trimester: 1, maternalChanges: 'Mood swings are common as hormones surge. You may feel bloated.', weeklyTip: 'Gentle exercise like walking can help boost your mood and energy.' },
  9: { size: 'Grape', sizeCompare: 'a grape', length: '2.3 cm', weight: '2 g', development: 'The embryo becomes a fetus; muscles allow first movements.', milestone: 'Now officially a fetus', trimester: 1, maternalChanges: 'Your waistline may be thickening. Hormonal changes continue.', weeklyTip: 'Avoid raw fish, unpasteurized cheese, and deli meats for food safety.' },
  10: { size: 'Kumquat', sizeCompare: 'a kumquat', length: '3.1 cm', weight: '4 g', development: 'Vital organs are functioning; nails start to grow.', milestone: 'Nails beginning to grow', trimester: 1, maternalChanges: 'You may notice veins becoming more visible on your breasts.', weeklyTip: 'Your first ultrasound may happen soon — you might hear the heartbeat!' },
  11: { size: 'Fig', sizeCompare: 'a fig', length: '4.1 cm', weight: '7 g', development: 'The baby can stretch, roll, and hiccup.', milestone: 'First hiccups', trimester: 1, maternalChanges: 'Morning sickness may start to ease as you approach the second trimester.', weeklyTip: 'Consider genetic screening tests if recommended by your provider.' },
  12: { size: 'Lime', sizeCompare: 'a lime', length: '5.4 cm', weight: '14 g', development: 'Reflexes develop; the baby may soon open and close fists.', milestone: 'Reflexes present', trimester: 1, maternalChanges: 'A tiny bump may be visible. Energy may start to return.', weeklyTip: 'The end of the first trimester! Your miscarriage risk drops significantly.' },
  13: { size: 'Lemon', sizeCompare: 'a lemon', length: '7.4 cm', weight: '23 g', development: 'Vocal cords form; fingerprints begin to develop.', milestone: 'Fingerprints forming', trimester: 2, maternalChanges: 'Second trimester begins! Many feel their best during this time.', weeklyTip: 'Start sleeping on your left side to improve blood flow to the baby.' },
  14: { size: 'Peach', sizeCompare: 'a peach', length: '8.7 cm', weight: '43 g', development: 'Facial expressions emerge; the baby can now suck their thumb.', milestone: 'Thumb sucking', trimester: 2, maternalChanges: 'Appetite may increase as nausea fades. Round ligament pain is possible.', weeklyTip: 'Begin gentle stretching or prenatal yoga to ease discomfort.' },
  15: { size: 'Apple', sizeCompare: 'an apple', length: '10.1 cm', weight: '70 g', development: 'The baby can sense light through closed eyelids.', milestone: 'Light sensitivity', trimester: 2, maternalChanges: 'You may feel baby flutters (quickening) soon, especially if this isn\'t your first.', weeklyTip: 'Consider announcing your pregnancy to friends and family if you haven\'t.' },
  16: { size: 'Avocado', sizeCompare: 'an avocado', length: '11.6 cm', weight: '100 g', development: 'The heart pumps about 25 quarts of blood each day.', milestone: 'Heart pumping strong', trimester: 2, maternalChanges: 'Your bump is more noticeable. You may feel the baby move for the first time.', weeklyTip: 'Schedule your second-trimester ultrasound (anatomy scan) for around week 20.' },
  17: { size: 'Pear', sizeCompare: 'a pear', length: '13 cm', weight: '140 g', development: 'Fat stores begin to develop; the skeleton hardens from cartilage to bone.', milestone: 'Bones hardening', trimester: 2, maternalChanges: 'Weight gain accelerates. You may experience backaches or round ligament pain.', weeklyTip: 'Use a pregnancy pillow for better sleep support.' },
  18: { size: 'Bell pepper', sizeCompare: 'a bell pepper', length: '14.2 cm', weight: '190 g', development: 'The baby can now hear sounds from inside the body.', milestone: 'Can hear sounds', trimester: 2, maternalChanges: 'Your belly is growing steadily. Heartburn and constipation are common.', weeklyTip: 'Talk and sing to your baby — they can hear you now!' },
  19: { size: 'Mango', sizeCompare: 'a mango', length: '15.3 cm', weight: '240 g', development: 'A protective coating called vernix covers the skin.', milestone: 'Vernix coating', trimester: 2, maternalChanges: 'Skin changes like dark patches or linea nigra may appear.', weeklyTip: 'Use sunscreen daily to minimize pregnancy-related skin pigmentation.' },
  20: { size: 'Banana', sizeCompare: 'a banana', length: '16.4 cm', weight: '300 g', development: 'Halfway there! The baby can now yawn and stretch.', milestone: 'Halfway point', trimester: 2, maternalChanges: 'Your anatomy scan happens around now — you can find out the sex if you want.', weeklyTip: 'Halfway there! Start thinking about a birth plan and maternity leave.' },
  21: { size: 'Carrot', sizeCompare: 'a carrot', length: '26.7 cm', weight: '360 g', development: 'The baby practices swallowing and digesting amniotic fluid.', milestone: 'Practicing swallowing', trimester: 2, maternalChanges: 'Swelling in feet and ankles is common. Stay hydrated and elevate feet.', weeklyTip: 'Start a pregnancy journal to document your journey.' },
  22: { size: 'Spaghetti squash', sizeCompare: 'spaghetti squash', length: '27.8 cm', weight: '430 g', development: 'Eyebrows and eyelids are forming; grip reflex develops.', milestone: 'Eyebrows forming', trimester: 2, maternalChanges: 'Braxton Hicks contractions may begin — usually painless practice contractions.', weeklyTip: 'Learn the signs of preterm labor so you know when to call your doctor.' },
  23: { size: 'Large mango', sizeCompare: 'a large mango', length: '28.9 cm', weight: '500 g', development: 'The baby can now hear your voice clearly; loud sounds may startle them.', milestone: 'Hearing your voice', trimester: 2, maternalChanges: 'Your center of gravity shifts — you may feel clumsier than usual.', weeklyTip: 'Wear supportive shoes to help with balance and foot pain.' },
  24: { size: 'Cantaloupe', sizeCompare: 'a cantaloupe', length: '30 cm', weight: '600 g', development: 'Lungs develop branches; the baby has a viable chance outside the womb.', milestone: 'Viability milestone', trimester: 2, maternalChanges: 'Your glucose screening test typically happens around weeks 24–28.', weeklyTip: 'Prepare for your glucose test by maintaining a balanced diet.' },
  25: { size: 'Cauliflower', sizeCompare: 'a cauliflower', length: '34.6 cm', weight: '660 g', development: 'Hair color and texture become determined; sense of equilibrium develops.', milestone: 'Hair growing', trimester: 2, maternalChanges: 'You may notice stronger fetal movements and kicks.', weeklyTip: 'Start thinking about a childbirth education class.' },
  26: { size: 'Lettuce head', sizeCompare: 'a head of lettuce', length: '35.6 cm', weight: '760 g', development: 'Eyes open for the first time; brain activity surges.', milestone: 'Eyes opening', trimester: 2, maternalChanges: 'Blood pressure may rise — your provider will monitor for preeclampsia.', weeklyTip: 'Track baby kicks daily to monitor your baby\'s wellbeing.' },
  27: { size: 'Cabbage', sizeCompare: 'a cabbage', length: '36.6 cm', weight: '875 g', development: 'The baby recognizes familiar voices and may respond with kicks.', milestone: 'Recognizing voices', trimester: 2, maternalChanges: 'Leg cramps and restless legs are common at night.', weeklyTip: 'Try magnesium-rich foods like spinach and almonds to ease leg cramps.' },
  28: { size: 'Eggplant', sizeCompare: 'an eggplant', length: '37.6 cm', weight: '1 kg', development: 'Third trimester begins; brain folds develop rapidly.', milestone: 'Third trimester', trimester: 3, maternalChanges: 'Third trimester! You may feel more tired and breathless as the baby grows.', weeklyTip: 'Start packing your hospital bag and finalize your birth plan.' },
  29: { size: 'Butternut squash', sizeCompare: 'butternut squash', length: '38.6 cm', weight: '1.15 kg', development: 'Muscles and lungs continue to mature; the baby practices breathing.', milestone: 'Breathing practice', trimester: 3, maternalChanges: 'Hemorrhoids, varicose veins, and heartburn may worsen.', weeklyTip: 'Eat fiber-rich foods and stay hydrated to ease constipation.' },
  30: { size: 'Cucumber', sizeCompare: 'a large cucumber', length: '39.9 cm', weight: '1.3 kg', development: 'Eyes can open and close; the baby can distinguish light and dark.', milestone: 'Eyes wide open', trimester: 3, maternalChanges: 'You may feel Braxton Hicks more frequently. Sleep becomes harder.', weeklyTip: 'Practice relaxation and breathing techniques for labor.' },
  31: { size: 'Coconut', sizeCompare: 'a coconut', length: '41.1 cm', weight: '1.5 kg', development: 'The baby passes water and produces urine; brain grows very fast.', milestone: 'Rapid brain growth', trimester: 3, maternalChanges: 'Shortness of breath is common as your uterus presses on your diaphragm.', weeklyTip: 'Use pillows to prop yourself up while sleeping for easier breathing.' },
  32: { size: 'Jicama', sizeCompare: 'a jicama', length: '42.4 cm', weight: '1.7 kg', development: 'Toenails are fully formed; the baby sleeps and wakes regularly.', milestone: 'Toenails complete', trimester: 3, maternalChanges: 'Your provider may check baby\'s position. Swelling increases.', weeklyTip: 'Count kicks daily and report any significant decrease to your provider.' },
  33: { size: 'Pineapple', sizeCompare: 'a pineapple', length: '43.7 cm', weight: '1.9 kg', development: 'Bones are hardening; the skull remains soft for delivery.', milestone: 'Bones hardening', trimester: 3, maternalChanges: 'Pelvic pressure increases as the baby drops lower.', weeklyTip: 'Install your car seat and have it checked at a local inspection station.' },
  34: { size: 'Cantaloupe', sizeCompare: 'a cantaloupe', length: '45 cm', weight: '2.1 kg', development: 'The central nervous system matures; lungs are nearly developed.', milestone: 'Lungs nearly ready', trimester: 3, maternalChanges: 'Group B strep test typically happens around weeks 35–37.', weeklyTip: 'Finalize childcare and pet care plans for when you go into labor.' },
  35: { size: 'Honeydew melon', sizeCompare: 'a honeydew melon', length: '46.2 cm', weight: '2.4 kg', development: 'Kidneys are fully developed; the liver processes waste.', milestone: 'Organs mature', trimester: 3, maternalChanges: 'Your belly may feel very tight. Frequent bathroom trips continue.', weeklyTip: 'Wash baby clothes and prepare the nursery. You\'re almost there!' },
  36: { size: 'Romaine lettuce', sizeCompare: 'a head of romaine', length: '47.4 cm', weight: '2.6 kg', development: 'The baby drops lower into the pelvis; most major development is complete.', milestone: 'Baby drops', trimester: 3, maternalChanges: 'Lightening — baby drops into pelvis. Breathing may get easier.', weeklyTip: 'Review the signs of labor with your partner or support person.' },
  37: { size: 'Swiss chard', sizeCompare: 'Swiss chard', length: '48.6 cm', weight: '2.9 kg', development: 'Officially early term; the baby practices breathing and grunting.', milestone: 'Early term', trimester: 3, maternalChanges: 'Increased discharge, backache, and loose joints are signs labor is near.', weeklyTip: 'Keep your phone charged and your hospital bag by the door.' },
  38: { size: 'Leek', sizeCompare: 'a leek', length: '49.8 cm', weight: '3.1 kg', development: 'The baby has firm grasp and toenails reach the toe tips.', milestone: 'Ready to arrive', trimester: 3, maternalChanges: 'You may feel nesting urges — preparing for baby\'s arrival.', weeklyTip: 'Rest as much as possible. Your baby could arrive any day now.' },
  39: { size: 'Mini watermelon', sizeCompare: 'a mini watermelon', length: '50.7 cm', weight: '3.3 kg', development: 'Full term! The baby continues building fat and is ready for birth.', milestone: 'Full term', trimester: 3, maternalChanges: 'Watch for water breaking, contractions, or bloody show.', weeklyTip: 'Stay calm and practice your breathing. Call your provider when labor begins.' },
  40: { size: 'Small pumpkin', sizeCompare: 'a small pumpkin', length: '51.2 cm', weight: '3.5 kg', development: 'Due date! The baby is ready to meet you.', milestone: 'Due date', trimester: 3, maternalChanges: 'You\'ve made it to your due date! Labor could start at any moment.', weeklyTip: 'Trust your body and your medical team. You\'re about to meet your baby!' },
};

export const TRIMESTER_LABELS = ['First Trimester', 'Second Trimester', 'Third Trimester'];
