import {
  getTotalPatients,
  getTotalDoctors,
  getActiveDoctors,
  getTotalAppointments,
  getPendingAppointments,
  getTodayAppointments,
  getCompletedAppointments,
  getCancelledAppointments,
  getVideoConsultations,
  getClinicConsultations,
  getMedicalRecordsCount,
  getPrescriptionCount,
  getTotalReviews,
  getPendingReviews,
  getTotalServices,
  getActiveServices,
  getAppointmentsPerMonth,
  getAppointmentStatusDistribution,
  getPatientsByAgeGroup,
  getPatientsByCity,
  getMostBookedServices,
  getDoctorWiseAppointments,
  getPatientsPerMonth,
  getAppointmentTypeDistribution,
  getPaymentStatusDistribution,
  getRevenuePerMonth,
  getAverageRating,
  getRecentAppointments,
  getRecentPatients,
} from "../repository/adminDashboardRepository.js";

export const getAdminDashboardService = async (year) => {
  const [
    totalPatients,
    totalDoctors,
    activeDoctors,
    totalAppointments,
    pendingAppointments,
    todayAppointments,
    completedAppointments,
    cancelledAppointments,
    videoConsultations,
    clinicConsultations,
    medicalRecordsCount,
    prescriptionCount,
    totalReviews,
    pendingReviews,
    totalServices,
    activeServices,
    appointmentsPerMonth,
    appointmentStatusDistribution,
    patientsByAgeGroup,
    patientsByCity,
    mostBookedServices,
    doctorWiseAppointments,
    patientsPerMonth,
    appointmentTypeDistribution,
    paymentStatusDistribution,
    revenuePerMonth,
    averageRating,
    recentAppointments,
    recentPatients,
  ] = await Promise.all([
    getTotalPatients(),
    getTotalDoctors(),
    getActiveDoctors(),
    getTotalAppointments(),
    getPendingAppointments(),
    getTodayAppointments(),
    getCompletedAppointments(),
    getCancelledAppointments(),
    getVideoConsultations(),
    getClinicConsultations(),
    getMedicalRecordsCount(),
    getPrescriptionCount(),
    getTotalReviews(),
    getPendingReviews(),
    getTotalServices(),
    getActiveServices(),
    getAppointmentsPerMonth(year),
    getAppointmentStatusDistribution(year),
    getPatientsByAgeGroup(),
    getPatientsByCity(),
    getMostBookedServices(year),
    getDoctorWiseAppointments(year),
    getPatientsPerMonth(year),
    getAppointmentTypeDistribution(year),
    getPaymentStatusDistribution(year),
    getRevenuePerMonth(year),
    getAverageRating(),
    getRecentAppointments(),
    getRecentPatients(),
  ]);

  const totalConsultations = clinicConsultations + videoConsultations;
  const completionRate = totalAppointments
    ? Number(((completedAppointments / totalAppointments) * 100).toFixed(1))
    : 0;
  const cancellationRate = totalAppointments
    ? Number(((cancelledAppointments / totalAppointments) * 100).toFixed(1))
    : 0;
  const videoShare = totalConsultations
    ? Number(((videoConsultations / totalConsultations) * 100).toFixed(1))
    : 0;
  const collectedRevenue = revenuePerMonth.reduce((sum, item) => sum + Number(item.revenue || 0), 0);

  return {
    cards: {
      totalPatients,
      totalDoctors,
      activeDoctors,
      totalAppointments,
      pendingAppointments,
      todayAppointments,
      completedAppointments,
      cancelledAppointments,
      videoConsultations,
      clinicConsultations,
      medicalRecordsCount,
      prescriptionCount,
      totalReviews,
      pendingReviews,
      totalServices,
      activeServices,
      averageRating,
      collectedRevenue,
      completionRate,
      cancellationRate,
      videoShare,
    },
    charts: {
      appointmentsPerMonth,
      appointmentStatusDistribution,
      patientsByAgeGroup,
      patientsByCity,
      mostBookedServices,
      doctorWiseAppointments,
      patientsPerMonth,
      appointmentTypeDistribution,
      paymentStatusDistribution,
      revenuePerMonth,
    },
    tables: {
      recentAppointments,
      recentPatients,
    },
  };
};
